[package]
name = "xcb-wm"
version = "0.4.0"
authors = [ "Armin Friedl <dev@friedl.net>" ]
description = "Rust implementation of xcb-wm - icccm and ewmh extensions for xcb"
readme = "README.md"
keywords = ["icccm", "ewmh", "xcb", "window", "x11"]
license = "MIT"
edition = "2018"
repository = "https://github.com/arminfriedl/xcb-wm"
homepage = "https://github.com/arminfriedl/xcb-wm"

[dependencies]
xcb = { git = "https://github.com/Philipp-M/rust-xcb.git", branch = "fix-quick-xml" }
paste = "1"
bitflags = "1.3.2"

[features]
icccm = []
ewmh = []

# Show documentations for `icccm` and `ewmh` features on http://docs.rs
# https://docs.rs/about/metadata
[package.metadata.docs.rs]
all-features = true
